#!/usr/bin/env bash

start_tmux() {
	selected=$1
	selected_name=$(basename "$selected" | tr . _)
	tmux_running=$(pgrep tmux)

	if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
		tmux new-session -s "$selected_name" -c "$selected"
		exit 0
	fi

	if ! tmux has-session -t="$selected_name" 2>/dev/null; then
		tmux new-session -ds "$selected_name" -c "$selected"
	fi

	tmux switch-client -t "$selected_name"
}

start_tmux /data/work/hcmus/alacritty
start_tmux /data/work/hcmus/winit
start_tmux /data/work/hcmus/client-toolkit
start_tmux /data/work/hcmus/thesis-tex
