#!/usr/bin/env bash

repos_path=~/tmux-sessionizer.local

[ -f $repos_path ] && readarray -t folders <$repos_path

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find ${folders[@]} -mindepth 1 -maxdepth 1 -type d | sk)
fi

if [[ -z $selected ]]; then
	exit 0
fi

echo $selected

source /data/repos/phnaharris-machos/scripts/start-tmux.sh

start_tmux $selected
