#!/usr/bin/env bash

repos_path=~/tmux-sessionizer.local

[ -f $repos_path ] && readarray -t folders <$repos_path

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find ${folders[@]} -mindepth 1 -maxdepth 1 -type d | fzf -m)
fi

source /data/repos/phnaharris-machos/scripts/start-tmux.sh

for selection in $selected; do
	if [[ -z $selection ]]; then
		continue
	fi

	echo $selection

	start_tmux $selection
done
