#!/usr/bin/env bash

source /data/repos/phnaharris-machos/scripts/start-tmux.sh

start_tmux /data/work/hcmus/alacritty
start_tmux /data/work/hcmus/winit
start_tmux /data/work/hcmus/client-toolkit
start_tmux /data/work/hcmus/thesis-tex
start_tmux /data/work/hcmus/egui
