#!/usr/bin/env bash

# icon: https://unicode-explorer.com/articles/cryptocurrency-unicode-symbols

cias=$(curl https://www.cias.wtf/mk/api/summary/55555 | jq '.floorPrice')
mias=$(curl https://www.cias.wtf/mk/api/summary/169 | jq '.floorPrice')
bgnt=$(curl -XPOST https://api3.bigint.co/getTokenFloorAndVolume -H "Content-Type: application/json; charset=utf-8" -d '{"tickName":"bgnt"}' | jq -r '.value | .floor')

text="$cias TIA | $mias Ξ | $bgnt Ξ"

echo '{"text":'\"$text\"',"tooltip":"$tooltip","class":"$class"}'
